(() => {
  'use strict';
  const data = window.EC212;
  const root = document.getElementById('main');
  const titles = {home:'ภาพรวมการทบทวน',plan:'แผนอ่าน 5 วัน',lessons:'บทเรียน',formulas:'สูตร & ตัวแปร',documents:'เอกสารต้นฉบับ'};
  const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const href = (file,page=1) => '../'+file.split('/').map(encodeURIComponent).join('/')+'#page='+page;
  const pdf = (file,page,label) => `<a class="pdf-link" href="${href(file,page)}" target="_blank" rel="noopener">${escape(label||'เปิด PDF หน้า '+page)} <span aria-hidden="true">↗</span></a>`;
  const taskIds=data.days.flatMap((day,i)=>day.tasks.map((_,j)=>`d${i+1}-t${j+1}`));
  const storageKey='ec212.summarize.study.v1';
  const localISO=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
  function validDate(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(value+'T12:00:00');return !Number.isNaN(date.valueOf())&&localISO(date)===value&&date.getFullYear()>=1900&&value<='2100-12-27';}
  let storageAvailable=true;
  let state={start:localISO(new Date()),done:[]};
  try{const raw=localStorage.getItem(storageKey);if(raw){const saved=JSON.parse(raw);if(saved&&typeof saved==='object'){if(validDate(saved.start))state.start=saved.start;if(Array.isArray(saved.done))state.done=[...new Set(saved.done.filter(id=>taskIds.includes(id)))];}}}catch{storageAvailable=false;}
  function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));storageAvailable=true;}catch{storageAvailable=false;}}
  save();
  let toastTimer;
  function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2700);}
  const progress=()=>Math.round(state.done.length/taskIds.length*100);
  const dayDone=day=>state.done.filter(id=>id.startsWith(`d${day}-`)).length;
  function dayDate(offset){const date=new Date(state.start+'T12:00:00');date.setDate(date.getDate()+offset);return date.toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'});}
  function storageHint(){return storageAvailable?'ความคืบหน้าบันทึกเฉพาะเบราว์เซอร์นี้ ไม่ซิงก์ข้ามอุปกรณ์':'เบราว์เซอร์นี้ไม่อนุญาตให้บันทึก ความคืบหน้าจะคงอยู่เฉพาะระหว่างเปิดหน้านี้';}
  function heading(kicker,title,description){return `<div class="heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${description}</p></div><span class="pill">MIDTERM · CHAPTER 01–04</span></div>`;}
  function home(){
    const next=data.days.findIndex((day,i)=>dayDone(i+1)<day.tasks.length),current=next<0?4:next;
    root.innerHTML=heading('A LITTLE PROGRESS, EVERY DAY','เข้าใจมหภาค พร้อมสอบกลางภาค','อ่านทีละบท เชื่อมสูตรกับเหตุผล แล้วลองทำด้วยตัวเอง')+`<section class="intro-panel"><div><div class="eyebrow">YOUR 5-DAY STUDY PLAN</div><h2>${next<0?'ครบ 5 วันแล้ว ทวนจุดที่ยังไม่แม่น':`วัน ${current+1} · ${data.days[current].title}`}</h2><p>${next<0?'กลับไปทวนสูตรและข้อผิดพลาดก่อนสอบได้เสมอ':`วันละ 4 ชั่วโมง · ${data.days[current].chapter} · เริ่มแผน ${dayDate(0)}`}</p><a class="btn lime" href="#plan/day-${current+1}">${next<0?'ดูแผนที่อ่านครบแล้ว':state.done.length?'ทบทวนต่อจากเดิม':'เปิดแผนอ่าน 5 วัน'} →</a></div><div class="ring" style="--progress:${progress()}%"><strong>${progress()}%</strong><span>${state.done.length}/${taskIds.length} กิจกรรม</span></div></section><div class="home-grid"><section class="panel"><div class="section-head" style="margin-top:0"><h2>เส้นทางการทบทวน</h2><a href="#plan">ดูตารางทั้งหมด ↗</a></div>${data.days.map((day,i)=>`<a class="day-preview" href="#plan/day-${i+1}"><span class="day-number">${dayDone(i+1)===day.tasks.length?'✓':'0'+(i+1)}</span><div><h3>${day.title}</h3><p>${day.chapter} · ${dayDate(i)} · ${dayDone(i+1)}/4 กิจกรรม</p></div><span class="arrow" aria-hidden="true">↗</span></a>`).join('')}</section><section class="panel"><div class="eyebrow muted">WHAT TO FOCUS ON</div><h2>4 บทที่ต้องเข้าใจ</h2>${data.chapters.map(c=>`<div class="mini-chapter"><span class="num">0${c.id}</span><div><a href="#lessons/${c.id}">${c.title}</a><p>${c.focus}</p></div></div>`).join('')}<div class="hint">เริ่มที่ <strong>Source</strong> → ทวนบันทึกเรียน → เปิดตำราเมื่อต้องการคำอธิบายเสริม</div></section></div><div class="section-head"><h2>เตรียมให้พร้อมก่อนทำโจทย์</h2></div><div class="chapter-grid"><a class="panel" href="#formulas"><div class="eyebrow muted">FORMULA NOTES</div><h3>สูตรที่จำ พร้อมเงื่อนไขที่ต้องรู้ ↗</h3><p class="muted">แยกภาษีสุทธิ ค่าอิสระ และตัวคูณให้ถูกก่อนแทนค่า</p></a><a class="panel" href="#documents"><div class="eyebrow muted">ORIGINAL MATERIALS</div><h3>เปิดต้นฉบับตรงหน้าที่อ่าน ↗</h3><p class="muted">สไลด์ 4 บท บันทึกเรียน 3 ชุด และตำราอ่านเสริม</p></a></div><div class="hint warning"><strong>ขอบเขตที่ใช้:</strong> บท 1–4 ตามเค้าโครงการสอนหน้า 5 เอกสารหน้า 6 มีข้อความขอบเขตสอบขัดกัน จึงควรยึดประกาศล่าสุดจากผู้สอนด้วย ${pdf('Course_Detail.pdf',5,'เปิดเค้าโครงการสอน')}</div>`;
  }
  function plan(){
    root.innerHTML=heading('20 HOURS · 5 DAYS','วางแผนวันนี้ อ่านจบทีละวัน','อ่าน 75 นาที · สรุป 60 นาที · ทำโจทย์ 75 นาที · ทวน 30 นาที รวม 4 ชั่วโมง ไม่รวมเวลาพัก')+`<section class="panel"><div class="plan-controls"><label class="date-field" for="start-date">วันเริ่มทบทวน <input type="date" id="start-date" min="1900-01-01" max="2100-12-27" value="${escape(state.start)}"></label><span class="plan-stats" id="plan-stats">${state.done.length} / ${taskIds.length} กิจกรรม · ${progress()}%</span></div><div class="progress-line" role="progressbar" aria-label="ความคืบหน้าการทบทวน" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${progress()}"><span style="--progress:${progress()}%"></span></div><p class="muted" id="storage-note" style="font-size:12px;margin-top:12px">${storageHint()} · แนะนำพัก 5–10 นาทีทุก 45–60 นาที</p></section><div class="plan-days">${data.days.map((day,i)=>`<section class="plan-day" id="day-${i+1}" tabindex="-1"><header class="plan-day-head"><span class="day-number">0${i+1}</span><div><h3>${day.title}</h3><p>${day.chapter} · <time class="day-date" data-offset="${i}">${dayDate(i)}</time></p></div><span class="pill" data-day-count="${i+1}">${dayDone(i+1)} / 4 เสร็จแล้ว</span></header>${day.tasks.map((t,j)=>{const id=`d${i+1}-t${j+1}`;return `<div class="task-row ${state.done.includes(id)?'done':''}"><input type="checkbox" id="${id}" data-task="${id}" ${state.done.includes(id)?'checked':''}><span class="duration">${t.minutes} นาที</span><label for="${id}"><strong>${t.title}</strong><span>${t.detail}</span></label><div class="pdf-links"><a class="pdf-link" href="#${t.route}">ทบทวนหัวข้อนี้ →</a>${t.file?pdf(t.file,t.page,'PDF หน้า '+t.page):''}</div></div>`;}).join('')}</section>`).join('')}</div>`;
    document.getElementById('start-date').addEventListener('change',e=>{if(!validDate(e.target.value)||!e.target.validity.valid){e.target.value=state.start;toast('กรุณาเลือกวันที่ที่ถูกต้อง');return;}state.start=e.target.value;save();document.querySelectorAll('.day-date').forEach(el=>el.textContent=dayDate(Number(el.dataset.offset)));document.getElementById('storage-note').textContent=storageHint();toast(storageAvailable?'ปรับวันที่อ่านทั้ง 5 วันแล้ว':'ปรับวันที่แล้ว แต่เบราว์เซอร์ไม่อนุญาตให้บันทึก');});
  }
  function lessons(chapterId){
    const chapter=data.chapters.find(c=>String(c.id)===chapterId);
    if(chapterId&&!chapter){root.innerHTML='<div class="empty"><h1>ไม่พบบทเรียนนี้</h1><p><a href="#lessons">กลับไปดูบทเรียนทั้งหมด →</a></p></div>';return;}
    if(!chapter){root.innerHTML=heading('UNDERSTAND BEFORE YOU MEMORIZE','บทเรียนก่อนสอบกลางภาค','เริ่มจากแนวคิด ฝึกคำนวณตามตัวอย่าง แล้วเปิดเอกสารต้นฉบับตรวจความเข้าใจ')+`<div class="chapter-grid">${data.chapters.map(c=>`<article class="chapter-card"><div class="chapter-no">CHAPTER 0${c.id} · ${c.sections.length} TOPICS</div><h2>${c.title}</h2><p>${c.description}</p><div class="card-actions"><a class="btn primary" href="#lessons/${c.id}">เริ่มบทเรียน →</a>${pdf(c.file,3,'เปิดสไลด์ต้นฉบับ')}</div></article>`).join('')}</div><div class="hint">สัดส่วนเวลาที่แนะนำ: บท 1 ประมาณ 15% · บท 2 ประมาณ 25% · บท 3 ประมาณ 35% · บท 4 ประมาณ 25% เป็นแนวทางแบ่งเวลา ไม่ใช่สัดส่วนข้อสอบที่ยืนยันแล้ว</div>`;return;}
    root.innerHTML=heading(`CHAPTER 0${chapter.id}`,chapter.title,chapter.description)+`<nav class="chapter-tabs" aria-label="เลือกบทเรียน">${data.chapters.map(c=>`<a class="${c.id===chapter.id?'selected':''}" ${c.id===chapter.id?'aria-current="page"':''} href="#lessons/${c.id}">บทที่ ${c.id}</a>`).join('')}<a href="#formulas">ดูสูตร & ตัวแปร ↗</a></nav><div class="lesson-layout"><div class="lesson-content">${chapter.sections.map((section,i)=>`<article class="panel" id="topic-${i+1}" tabindex="-1"><h3>${i+1}. ${section.title}</h3>${section.body}${section.example?`<div class="example"><div class="tag">${section.example.title}</div><ol class="steps">${section.example.steps.map(step=>`<li>${step}</li>`).join('')}</ol></div>`:''}${section.chart?chart(section.chart):''}<div class="pdf-links">${pdf(chapter.file,section.page,'เปิด Source หน้า '+section.page)}</div></article>`).join('')}<div class="panel"><h3>พร้อมไปต่อหรือยัง?</h3><p class="muted" style="margin:10px 0 17px">ลองปิดตัวอย่างแล้วทำใหม่ ถ้ายังติดให้จดขั้นที่ผิด ก่อนกลับไปติ๊กแผนอ่าน</p><div class="pdf-links"><a class="btn primary" href="#plan">กลับไปแผนอ่าน</a><a class="btn" href="${chapter.id<4?'#lessons/'+(chapter.id+1):'#formulas'}">${chapter.id<4?'บทถัดไป':'ทวนสูตรทั้งหมด'} →</a></div></div></div><aside class="lesson-aside"><div class="panel"><div class="eyebrow muted">IN THIS CHAPTER</div><h3 style="margin:8px 0">อ่านให้ครบ เชื่อมให้เป็น</h3>${chapter.sections.map((s,i)=>`<a class="toc-link" href="#lessons/${chapter.id}/topic-${i+1}">${i+1}. ${s.title}</a>`).join('')}<div class="hint">อ่านสรุปแล้ว ควรตรวจกราฟและนิยามจากต้นฉบับทุกครั้งที่พบสัญลักษณ์ต่างกัน</div></div></aside></div>`;
  }
  function formulas(){root.innerHTML=heading('FORMULAS & VARIABLES','จำสูตร พร้อมเข้าใจตัวแปร','กดแต่ละกลุ่มเพื่อเปิดสูตร และใช้พจนานุกรมตัวแปรด้านล่างตรวจความหมาย')+`<div class="hint warning" style="margin:0 0 23px"><strong>อ่านก่อนแทนค่า:</strong> เว็บนี้ใช้ T เป็นภาษีรวม และ R เป็นเงินโอน → Yd = Y − T + R หากโจทย์ใช้ T เป็นภาษีสุทธิแล้ว ให้ใช้ Yd = Y − T</div><div class="formula-grid">${data.formulas.map((f,i)=>`<details class="formula-card" ${i<2?'open':''}><summary><span><strong>${f.title}</strong><small>${f.subtitle}</small></span></summary><div class="formula-body"><div class="equation">${escape(f.formula)}</div><p>${f.note}</p><div class="pdf-links" style="margin-top:15px">${pdf(f.file,f.page)}</div></div></details>`).join('')}</div><div class="section-head" id="variables"><h2>พจนานุกรมตัวแปร</h2><span class="topic-chip">ตัวใหญ่ ตัวเล็ก และตัวห้อยมีความหมาย</span></div><div class="hint"><strong>ตัวอย่าง:</strong> I = 25 + 0.1Y → I คือการลงทุนรวม, Iₐ = 25 คือส่วนอิสระ และ i = 0.1 คือ MPI เมื่อ Y เพิ่ม 100 การลงทุนจะเพิ่ม 10 โดย Iₐ คงเดิม</div>${data.variables.map(g=>`<section class="panel variable-group"><h3>${g.title}</h3><div class="table-wrap"><table><thead><tr><th>สัญลักษณ์</th><th>ความหมาย</th><th>ช่วยจำ / เงื่อนไข</th></tr></thead><tbody>${g.rows.map(row=>`<tr><td class="symbol">${escape(row[0])}</td><td>${escape(row[1])}</td><td>${escape(row[2])}</td></tr>`).join('')}</tbody></table></div></section>`).join('')}`;}
  function documents(){root.innerHTML=heading('GO TO THE SOURCE','เอกสารต้นฉบับ','เปิดไฟล์ในแท็บใหม่ พร้อมเลขหน้าแนะนำสำหรับแต่ละหัวข้อ')+`<div class="hint" style="margin:0 0 23px">ปุ่มเชื่อมกับ PDF ในโฟลเดอร์ EC212 โดยตรง เลขหน้าที่ระบุเป็น <strong>หน้า PDF</strong> หากโปรแกรมอ่านไม่ข้ามหน้าอัตโนมัติ ให้พิมพ์เลขหน้าที่ระบุ บันทึกลายมือเป็นภาพ ควรเปิดดูต้นฉบับเมื่อทวนสูตร</div>${['เอกสารหลัก','บันทึกการเรียน','ตำราอ่านเสริม'].map(group=>`<div class="section-head"><h2>${group}</h2></div><div class="documents">${data.documents.filter(doc=>doc.group===group).map(doc=>`<article class="document"><span class="document-icon" aria-hidden="true">PDF</span><div><h3>${doc.title}</h3><p>${doc.detail}</p></div><a class="btn" href="${href(doc.file,doc.page)}" target="_blank" rel="noopener" aria-label="เปิด ${escape(doc.title)} หน้า ${doc.page} ในแท็บใหม่">เปิดหน้า ${doc.page} ↗</a></article>`).join('')}</div>`).join('')}<div class="hint warning">เก็บโฟลเดอร์ Summarize ไว้ภายใน EC212 คู่กับ Source, Lecture_Notes และ TextBook เพื่อให้ลิงก์เดิมใช้ได้ หากย้ายเว็บเพียงโฟลเดอร์เดียว ปุ่มเปิดเอกสารจะหาไฟล์ไม่พบ</div>`;}
  function chart(kind){
    const config={ppf:{title:'เส้นความเป็นไปได้ในการผลิต',y:'ข้าว',x:'รถยนต์',maxX:10,maxY:12,caption:'ตัวอย่างจุดบน PPF จากสไลด์: (0,10), (6,5), (7,3), (8,0) เส้นเชื่อมใช้ประกอบการอ่านต้นทุนค่าเสียโอกาส'},cross:{title:'ดุลยภาพรายได้: Y = DAE',y:'DAE',x:'Y',maxX:600,maxY:600,caption:'เส้น DAE = 140 + 0.6Y ตัดเส้น 45° ที่ Y = 350; ผลผลิตสูงกว่านี้ทำให้สินค้าคงคลังที่ไม่ได้ตั้งใจเพิ่ม'},injection:{title:'ส่วนอัดฉีดเท่ากับส่วนรั่วไหล',y:'Injection / Withdrawal',x:'Y',maxX:600,maxY:300,minY:-60,caption:'ที่ Y = 350 ทั้งสองเส้นมีค่า 125 ตรงกับดุลยภาพจากวิธี Y = DAE'},gap:{title:'ช่องว่างรายได้และช่องว่างรายจ่าย',y:'DAE',x:'Y',maxX:600,maxY:600,caption:'Yᴱ = 350 และ Yꜰ = 450: ช่องว่างรายได้ = 100; DAE(450) = 410 จึงมีช่องว่างรายจ่าย = 40'}}[kind];
    const xmin=65,xmax=515,ymin=50,ymax=500,minY=config.minY||0;
    const x=v=>xmin+v/config.maxX*(xmax-xmin),y=v=>ymax-(v-minY)/(config.maxY-minY)*(ymax-ymin);
    const line=(x1,y1,x2,y2,color,dash='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="2" ${dash?'stroke-dasharray="'+dash+'"':''}/>`;
    let svg=`<svg viewBox="0 0 640 615" role="img" aria-label="${config.title}"><title>${config.title}</title><text x="65" y="26" fill="#42594c" font-size="17" font-family="sans-serif">${config.y}</text>`;
    for(let k=0;k<=4;k++){const value=config.maxX*k/4,yvalue=minY+(config.maxY-minY)*k/4;svg+=line(x(value),ymin,x(value),ymax,'#e2e8e3')+line(xmin,y(yvalue),xmax,y(yvalue),'#e2e8e3')+`<text x="${x(value)}" y="525" text-anchor="middle" fill="#637271" font-size="16">${value}</text><text x="52" y="${y(yvalue)+5}" text-anchor="end" fill="#637271" font-size="16">${yvalue}</text>`;}
    svg+=line(xmin,y(0),xmax+13,y(0),'#81988a')+line(xmin,ymin,xmin,ymax,'#81988a')+`<text x="550" y="525" fill="#42594c" font-size="17">${config.x}</text>`;
    const curve=(points,color)=>`<polyline points="${points.map(p=>x(p[0])+','+y(p[1])).join(' ')}" fill="none" stroke="${color}" stroke-width="3" stroke-linejoin="round"/>`;
    if(kind==='ppf'){
      svg+=curve([[0,10],[6,5],[7,3],[8,0]],'#176d50');
      [[0,10,'A'],[6,5,'B'],[7,3,'C'],[8,0,'D']].forEach(([a,b,l])=>svg+=`<circle cx="${x(a)}" cy="${y(b)}" r="4" fill="#176d50"/><text x="${x(a)+9}" y="${y(b)-8}" fill="#176d50" font-size="15">${l} (${a}, ${b})</text>`);
      svg+='<text x="65" y="568" fill="#176d50" font-size="17">PPF · ทรัพยากรและเทคโนโลยีคงเดิม</text>';
    }else if(kind==='injection'){
      svg+=curve([[0,90],[600,150]],'#176d50')+curve([[0,-50],[600,250]],'#a0683b');
      svg+=line(x(350),y(0),x(350),y(125),'#8da699','5 4')+`<circle cx="${x(350)}" cy="${y(125)}" r="5" fill="#176d50"/><text x="${x(350)+10}" y="${y(125)-12}" fill="#172a29" font-size="15">E (350, 125)</text>`;
      svg+='<text x="65" y="560" fill="#176d50" font-size="17">Injection = 90 + 0.1Y</text><text x="65" y="590" fill="#a0683b" font-size="17">Withdrawal = −50 + 0.5Y</text>';
    }else{
      svg+=curve([[0,0],[600,600]],'#90a797')+curve([[0,140],[600,500]],'#176d50');
      svg+=line(x(350),y(0),x(350),y(350),'#8da699','5 4')+`<circle cx="${x(350)}" cy="${y(350)}" r="5" fill="#176d50"/><text x="${x(350)-80}" y="${y(350)-16}" fill="#176d50" font-size="15">E (350, 350)</text>`;
      if(kind==='gap'){svg+=line(x(450),y(0),x(450),y(450),'#a0683b','5 4')+line(x(450),y(410),x(450),y(450),'#a0683b');svg+=`<circle cx="${x(450)}" cy="${y(410)}" r="4" fill="#a0683b"/><text x="${x(450)+12}" y="${y(450)+6}" fill="#885125" font-size="14">Gap = 40</text>`;svg+=line(x(350),y(50),x(450),y(50),'#a0683b')+`<text x="${x(400)}" y="${y(50)-9}" text-anchor="middle" fill="#885125" font-size="14">ΔY = 100</text>`;}
      svg+='<text x="65" y="560" fill="#176d50" font-size="17">DAE = 140 + 0.6Y</text><text x="65" y="590" fill="#637271" font-size="17">เส้น 45° : Y = DAE</text>';
    }
    return `<figure class="chart" tabindex="0" aria-label="${config.title} เลื่อนซ้ายขวาได้บนจอเล็ก"><div class="chart-scroll-hint">← เลื่อนซ้าย–ขวาเพื่อดูกราฟเต็ม →</div>${svg}</svg><figcaption>${config.caption}</figcaption></figure>`;
  }
  function setTasks(changes){
    if(!Array.isArray(changes)||changes.some(c=>!c||!taskIds.includes(c.id)||typeof c.done!=='boolean'))throw new Error('รหัสกิจกรรมหรือสถานะไม่ถูกต้อง');
    const done=new Set(state.done);changes.forEach(c=>c.done?done.add(c.id):done.delete(c.id));state.done=[...done];save();
  }
  function updatePlanProgress(){
    document.querySelectorAll('[data-task]').forEach(input=>{const checked=state.done.includes(input.dataset.task);input.checked=checked;input.closest('.task-row').classList.toggle('done',checked);});
    const stats=document.getElementById('plan-stats');if(stats)stats.textContent=`${state.done.length} / ${taskIds.length} กิจกรรม · ${progress()}%`;
    const bar=document.querySelector('[role="progressbar"]');if(bar){bar.setAttribute('aria-valuenow',progress());bar.firstElementChild.style.setProperty('--progress',progress()+'%');}
    document.querySelectorAll('[data-day-count]').forEach(el=>el.textContent=`${dayDone(Number(el.dataset.dayCount))} / 4 เสร็จแล้ว`);
    const note=document.getElementById('storage-note');if(note)note.textContent=storageHint();
  }
  root.addEventListener('change',e=>{if(!e.target.matches('[data-task]'))return;setTasks([{id:e.target.dataset.task,done:e.target.checked}]);updatePlanProgress();toast(storageAvailable?'บันทึกความคืบหน้าแล้ว':'อัปเดตแล้ว แต่เบราว์เซอร์ไม่อนุญาตให้บันทึก');});
  function render(navigate=false){
    const parts=location.hash.slice(1).split('/');let section=parts[0]||'home';if(!Object.hasOwn(titles,section))section='home';
    document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav===section;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
    document.getElementById('breadcrumb').textContent=titles[section];document.title=`${titles[section]} · EC212 Study Room`;
    ({home,plan,lessons:()=>lessons(parts[1]),formulas,documents}[section])();
    if(navigate)requestAnimationFrame(()=>{const anchor=section==='plan'?parts[1]:section==='lessons'?parts[2]:parts[1];const target=anchor?document.getElementById(anchor):null;if(target){target.focus({preventScroll:true});target.scrollIntoView({block:'start',behavior:'instant'});}else{root.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}});
  }
  window.addEventListener('hashchange',()=>render(true));
  window.addEventListener('storage',event=>{if(event.key!==storageKey||!event.newValue)return;try{const saved=JSON.parse(event.newValue);if(!saved||!validDate(saved.start)||!Array.isArray(saved.done))return;state={start:saved.start,done:[...new Set(saved.done.filter(id=>taskIds.includes(id)))]};render();}catch{/* Ignore invalid data from another tab. */}});
  render(Boolean(location.hash));
  // Optional agent-browser support shares the exact same local progress action.
  if(document.modelContext?.registerTool){
    const lifecycle=new AbortController();
    const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Ordinary browsers use the UI. */}};
    register({name:'read_study_progress',description:'อ่านวันเริ่มและความคืบหน้าแผน EC212 ในเบราว์เซอร์นี้',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({start:state.start,completed:[...state.done],total:taskIds.length,percent:progress(),persisted:storageAvailable})});
    register({name:'set_study_task_completion',description:'กำหนดสถานะกิจกรรมที่อ่านเสร็จหรือยังไม่เสร็จ แล้วบันทึกในเบราว์เซอร์นี้',inputSchema:{type:'object',properties:{changes:{type:'array',items:{type:'object',properties:{id:{type:'string',enum:taskIds},done:{type:'boolean'}},required:['id','done'],additionalProperties:false}}},required:['changes'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{setTasks(input?.changes);render();return {completed:[...state.done],percent:progress(),persisted:storageAvailable};}});
    window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  }
})();
